### ISSUE TITLE
[Carlos Palomares] ( w2-project_pandas)

### ISSUE THREAD

**Issue by CarlosPalomaresGarcia** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#11]
https://github.com/CarlosPalomaresGarcia/Limpieza_datos.git

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Carlos. Se nota que vas interiorizando cosas y ha habido muchas cosas que me han gustado mucho en tu proyecto. Te paso algunos comentarios:

-	En cuanto al repositorio, buena distribución, con carpetas y readme. Eso sí, intenta que el readme quede claro porque sobre todo la parte final no se entiende muy bien, y debería no sólo entenderse en pocas frases, también resultar atractivo para quien llega a tu repo (lo harán los recruiters cuando estés en procesos, por eso es importante).
-	Muy bien comentado el notebook, usando las celdas de markdown y los propios comentarios en celdas de código.
-	Intenta afinar más las funciones porque se te están escapando casos, especialmente en la que le aplicas a Age.
-	Han faltado algunas columnas por tratar, como Date, imagino que por falta de tiempo. Recuerda que cuando terminas viene bien que cambies los tipos de dato a category en los casos en que se pueda, y hagas el “downcast” de los ints y float si es posible, con el fin de optimizar el DF antes de pasarlo a csv, lo cual también te ha faltado.

En general, muy buen trabajo. Me parece que has conseguido tener la organización que no te vi el otro día, además de pillar muchas cosas que antes no pillabas, y se nota. Lástima que no lo remataras, pero de verdad, sigue así!
