### ISSUE TITLE
[Alexis Camarasa]( w2-project_pandas)

### ISSUE THREAD

**Issue by camarasa1987** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#12]
https://github.com/camarasa1987/sharkAlexis.git

**Comment by CharlyKill7** [comment]
En general, buen proyecto Alexis. Se nota que estás interiorizando cosas poco a poco, y las que empiezas a controlar las usas bien. Te animo a intentar otras cosas que no controles para así aumentar tus habilidades de manejo de DFs. Algunos comentarios sobre el proyecto:

- Intenta tener mejor organización en el repo, usando carpetas o borrando archivos que has actualizado (tienes varios main). El readme debe ser una sinopsis y quizá es demasiado largo. En el futuro, intenta que cuente la idea principal de lo que hay en los notebooks, y ya dentro de esos notebooks te extiendes y explicas el resto. Si puedes, intenta ser más limpio en el notebook principal. Te recomiendo hacer las pruebas en un notebook en sucio, y después copiar el trozo limpio de código y acompañarlo de una explicación en markdown o en comentario. Y acuérdate de incluir los archivos .csv en el .gitignore, y hacerlo antes de subir ningún csv para que no aparezcan en GitHub. 
- Ya entrando en el código, usas varias veces str.capitalize().str.title(), y no estoy seguro de si entiendes bien esos dos métodos. Capitalize convierte la primera letra de la string en mayúscula y Title hace lo mismo pero con todas las palabras, y además asegura que el resto de la palabra sea minúscula. Es decir, no es necesario usar las dos, y parece mejor usar title que capitalize para tu propósito. En el mismo sentido, usas ataque["Area"].str.rstrip().str.lstrip(), que es eliminar espacios en blanco a la izquierda primero y a la derecha después, cuando usando str.strip(), simplemente, consigues lo mismo en un solo paso y por los dos lados.
- Me gusta cómo has aprovechado las Unamed para convertirlas en rangos de edad y franja horaria. Así podemos filtrar por siglos, por adultos o por ataques nocturnos fácilmente. Eso sí, me habría gustado que hubieras intentado hacer algo más que rellenar los nulos con algunas columnas, como por ejemplo Species, que tiene muchos valores únicos que podrías haber unificado.
- Finalmente, te falta pasarlo a un csv limpio al final, además de que podrías haber ajustado los tipos de dato a category o hacerles un downcast en caso de ser float o int, optimizando el DF y reduciendo su espacio en memoria.
Respecto a la exposición que hiciste de proyecto, algunos consejos para el futuro:
- Exponer de pie es mucho mejor que sentado desde un punto de vista de captar la atención de la audiencia.
- Intenta ir más al grano, con el fin de conseguir un mejor ritmo que enganche al público.
- Si puedes, intenta leer menos y tenerlo más en la cabeza, para explicarlo con palabras propias. Si lo entiendes bien, queda mucho mejor después. 
- En general, en el trabajo sueles presentar a un directivo a quien no le interesa tu código, por lo que te recomiendo explicar lo que has hecho sin entrar en lo técnico, al menos a partir de ahora que todos los proyectos serán distintos de Sharks.
- Intenta reducir el tiempo. En futuras exposiciones, incluido el proyecto final, tendrás entre 3 y 5 minutos, pero en este estuviste 12 minutos. No pasa nada, pero para el futuro, que lo sepas.

En todo caso, sigue así porque se nota que vas a aprendiendo cada vez más, pero eso, te animo a atreverte a probar cosas incluso aunque a veces no tengan sentido. Te ayudará a entender mejor el conjunto.
