### ISSUE TITLE
[Carlos Clemente] w2-project_pandas

### ISSUE THREAD

**Issue by Carlosclementegarcia** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#13]
https://github.com/Carlosclementegarcia/PROYECTO-SHARKS-CARLOS.git

**Comment by CharlyKill7** [comment]
En líneas generales, buen proyecto, Carlos. Algunos comentarios al respecto:

- El repositorio requiere mucho trabajo. El archivo con el jupyter notebook que has usado, intenta renombrarlo como main o principal, o algo así. Además, es una buena práctica incluirlo en una carpeta de “notebooks”. Pero lo que no puede faltar en un repositorio de GitHub es el Readme, porque es como tener un manuscrito sin portada ni información exterior. En él debes hacer una especie de sinopsis del proyecto, para que de un vistazo cualquiera sepa de qué va el repo. Imagino que no te quedó demasiado tiempo, pero esto es importante que lo hagas porque los reclutadores entran a vuestros repositorios y una buena organización puede resultar decisiva a la hora de contratar.
- Acuérdate de que para imprimir DataFrames no hace falta ponerle el print, y además de esta forma se ven peor que si usas display o simplemente lo escribes en la última línea de la celda.
-	A veces generas variables como “resultados_1” para ver el índice de la fila y poder cambiarlo. No hace falta que inicialices una variable para eso, con poner df[df['Sex '] == 'N'], por ejemplo, ya te da la misma información sin tener que crear variables ni ocupar espacio en memoria. Además, si lo haces intenta no repetir nombres para las variables para evitar posibles errores.
-	Cuando usas pd.to_datetime(df['Date'],errors='coerce'), el parámetro coerce convierte a nulos los datos que no pueda convertir a tipo fecha. Por eso, después de aplicar esto, tienes que volver a gestionar los nuevos nulos.

Aunque falta terminar el proyecto, la verdad es que has progresado mucho esta semana y eso es lo más importante. La actitud supera a la aptitud en este bootcamp, y te aseguro que no es una frase hecha. Precisamente por eso, te recomiendo rematar el proyecto cuando encuentres un hueco, para asegurarte de interiorizar cómo optimizar el DF con tipos de datos adecuados o cómo pasarlo a csv. Ánimo y sigue así!

**Comment by Carlosclementegarcia** [comment]
Muchas gracias Carlos.
Seguimos peleando.
