### ISSUE TITLE
[Eduardo Goicoechea] Panda Cleanup project

### ISSUE THREAD

**Issue by Hrodward88** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#14]
https://github.com/Hrodward88/Sharkwork-.git

**Comment by CharlyKill7** [comment]
Buen proyecto, Eduardo, se nota el esfuerzo que le has puesto. Permíteme algunos comentarios:

-	En cuanto al repositorio, intenta reducir la extensión del readme. Debe ser una sinopsis y no entrar en detalle. Trata de centrarte en dar una explicación atractiva de lo que podrán ver el código. Recuerda incluir los archivos en carpetas para una mejor organización.
-	Lo mismo te recomiendo en el notebook, intenta tener una mejor organización y comentado. Entiendo que hay poco tiempo y que probablemente te centraste en acabar otras cosas, pero tenlo en cuenta para el futuro porque son buenas prácticas y puede decantar la balanza entre cogerte a ti o a otro si entran en tu GitHub.
-	Me ha hecho mucha gracia esta línea de código: 
Sharkattacks = Sharkattacks.fillna({'Case number': 'Look at the end of the table', 'Year':'Manny moons ago', 'Type': 'Asking for it', 'Country': 'Carmen Sandiego', 'Area': '51', 'Location': 'Wally', 'Activity': 'Water activity', 'Name': 'John/Jane Doe', 'Sex': '<--Who´s asking?', 'Age': '0 to 99', 'Injury': 'Ouch', 'Fatal': 'Schrödinger', 'Time':'Is relative', 'Species': 'Ellasmobranquii sp', 'Investigator or Source': 'Mulder & Scully', 'Href formula' : '-->'})
Sin embargo, es posible que haya mejores maneras de rellenar los nulos. Te invito a que pienses si hay formas de hacerlo que permitan una columna más homogénea, tanto en tipo de dato como en sus valores.
-	Me gusta que pruebes cosas, como la visualización de correlaciones o el One Hot Encoding. Siempre viene muy bien explorar, pero también hay que saber priorizar, y quizá hubiera sido mejor terminar lo esencial de la limpieza antes de ir más allá. 
- 
En general, el proyecto es mejorable. Aun así, se nota que hay trabajo detrás y eso es lo más importante. Sigue trabajando así porque vas bien, y eso se notará cada vez más en cada proyecto. Ánimo!
