### ISSUE TITLE
[David Aparicio] (w2-project_pandas)

### ISSUE THREAD

**Issue by dapafer** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#15]
https://github.com/dapafer/data-cleaning-pandas

**Comment by CharlyKill7** [comment]
Buen proyecto, David. Me gusta tu organización y cómo planteas las cosas. Algunos comentarios:
-	Muy buen repo. Todo en carpetas, bien titulado y organizado. El readme es correcto, tiene una buena extensión aunque quizá no pondría el apartado “Conclusion”. 
-	En cuanto al relleno de nulos que haces al principio, te recomiendo que mires si puedes rellenarlos con información de otras columnas antes de hacer el fillna masivo. Además, ten en cuenta que igual es mejor rellenar con 0 (si tiene sentido) en las columnas de int o float, y con strings (‘unknow’ o ‘no info’) en las columnas de tipo object. Así aseguras cierta homogeneidad de los tipos de dato.
-	Muy bien comentado, tanto la exploración como la limpieza. Usas bien tanto el markdown como los comentarios y queda claro donde estás y qué vas haciendo.
-	Aunque el DF termina sin nulos y con algunas columnas cambiadas, hay muchas otras sin tratamiento. Por ejemplo, Species o Time, terminan igual que estaban. Precisamente este proyecto va de limpiar esas columnas y te recomiendo volver sobre él a intentar múltiples formas de limpiar columnas. Es algo importante para un analista de datos.
-	Recuerda que cuando terminas viene bien que cambies los tipos de dato a category en los casos en que se pueda, y hagas el “downcast” de los ints y float si es posible, con el fin de optimizar el DF antes de pasarlo a csv.

En general, el proyecto está bien salvo por el hecho de que se queda en la superficie. Intenta ir mas allá en adelante; aquí estamos precisamente para equivocarnos, probar cosas, aprender. Sigue con esas buenas prácticas que tienes pero intenta añadir a tu baraja esa carta de profundidad que te falta. Ánimo!
