### ISSUE TITLE
[Ignacio Romero][w2-project_pandas]

### ISSUE THREAD

**Issue by Linxx333** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#16]
https://github.com/Linxx333/Data-Cleaning-Shark-Attacks

**Comment by CharlyKill7** [comment]
En general, muy buen proyecto, Nacho. Se nota que lo entiendes bien, ya que usas los fundamentos para todo, sin depender demasiado de métodos, lo cual te vendrá genial siempre. Eso se ve claramente en las funciones, que además comentas demostrando buenas prácticas. De hecho, intenta guardar en un archivo aparte de funciones al menos aquellas que son susceptibles de servirte en el futuro (ej: la de contar nulos), y así recuperas el archivo para tus próximos proyectos y eso que te ahorras. 

Por otro lado, buena actitud la de no rellenar a la ligera, buscando en internet lo que parece más probable. Hay quien te diría que eso sigue siendo inventar, pero yo estoy de acuerdo con esa línea de pensamiento. 

Como ya has podido comprobar, Sharks es eterno, pero creo que aun hay columnas que podrías haber limpiado mejor todavía. Si compruebas el estado de las columnas al final de la limpieza, verás valores heterogéneos que seguramente pueden transformarse más. Imagino que el cansancio también influye porque, al final, después de los fregaos en los que te has metido, me he quedado con ganas de verte rematar el DF cambiando los tipos de dato a categoría en los casos en los que es posible (ej: Provoked/Unprovoked). 

De hecho, en caso de que alguna columna hubiera podido pasarse a entero o a float, te recomiendo hacerlo. Incluso si a veces algo no tiene mucho sentido, aquí estamos para aprender y te recomiendo hacerle de todo y muy variado a los DF aunque sea por probar. Así podrías haber hecho el 'downcast' para optimizar el tamaño del DF y el espacio que ocupa en memoria.

En definitiva, gran proyecto, Nacho. Sigue así, que vas a genial!
