### ISSUE TITLE
[Jose Luis Reguera Alvarez] (w2-project_pandas)

### ISSUE THREAD

**Issue by jose-luis666** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#18]
https://github.com/jose-luis666/REPOSITORIO-PROYECTO.git

**Comment by OrianAmpuero** [comment]
Bien selu! hay que ir puliendo código pero en general vas bien, te animo a seguir practicando distintos métodos pero entendiendo el proceso. En cuanto al repo, te faltó readme y organización de archivos en carpetas.

**Comment by jose-luis666** [comment]
Gracias Oriana!

Qué raro, hice el read me y las carpetas. De hecho las comenté cuando salí
a presentar el proyecto.

Supongo que quizá he cargado mal la carpeta, ahora lo reviso. Pero sí,
recuerdo que las hice :(

Muchas gracias!!
