### ISSUE TITLE
[Augusto Abad Varela](IRONHACK_Sharks)

### ISSUE THREAD

**Issue by gusavato** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#19]
https://github.com/gusavato/1_IRONHACK_Sharks

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Gus. Se nota que no sólo controlas el código necesario, también demuestras procesos mentales organizados y de cierta profundidad. Unos cuantos comentarios que he ido anotando:

- Buen repo, sobre todo la organización de carpetas. Lo único que tengo que decirte es que mi TA me dijo del readme que era muy escueto, como ya te comenté. Yo no estoy de acuerdo y por eso lo hice así, pero te lo digo para que tengas las dos opiniones. Ya terminado el bootcamp y unos cuantos proyectos, aun no tengo claro cómo hacer el readme perfecto.
- El archivo de funciones está genial, y te confieso que me he guardado algunas para futuras limpiezas. Me gusta cómo vas comentando tanto en el notebook en markdown, como las propias funciones: son muy buenas prácticas. 
- Que uses visualización para verlo más claro es una buena costumbre que además te hace practicar desde ya la visualización en Python.
- Por ponerte algún "pero". Por ejemplo, en la columna Country, había países que además de aparecer bien (ej: ‘EGYPT’) también aparecían mal escritos o con espacios (‘EGYPT ‘). Por ser perfeccionista, te animo a que ya que lo haces todo tan a conciencia, lo hagas hasta el final y ataques incluso los casos particulares cuando sea posible. Algo parecido podrías haber hecho en Species que, aunque entiendo tu razonamiento de que hay demasiados valores únicos, muchos contenían “white”, “bull”, etc. Son palabras que podían dar una pista y permitir agrupar fácilmente muchos de ellos.
- Al final, también podrías haber intentado cambiar los tipos de dato para optimizar el DF. Por ejemplo, en los casos en que fuera posible pasarlo a category. Así reduces el espacio en memoria que ocupa el DF y, en proyectos de millones de filas, esto podría resultar decisivo.
En cuanto a la exposición:
- Exponer de pie es mucho mejor que sentado desde un punto de vista de captar la atención de la audiencia.
- Intenta reducir el tiempo. En futuras exposiciones, incluido el proyecto final, tendrás entre 3 y 5 minutos, pero en este estuviste unos 15. No pasa nada pero, para el futuro, que lo sepas. Puedes lograrlo explicando en 1-2 frases cada paso, sin entrar en detalle, porque además en el trabajo sueles presentar a un directivo a quien no le interesa tu código. Así ganas tiempo y mantienes el interés del público no tech. 

En definitiva, muy buen proyecto. Creo que no hace falta que te lo diga, pero sigue así que vas como un cohete!
