### ISSUE TITLE
[Luis Galdeano] (Project_Pandas)

### ISSUE THREAD

**Issue by LuisGaldeano** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#2]
https://github.com/LuisGaldeano/Shark_Attack_Project.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Luis!! Todo detallado en cuanto a la explicación de tu limpieza, con el repo en general y el proceso. Sigue a tope que se nota el curro detrás.
