### ISSUE TITLE
[Jesus Guardia Ramirez] (Sharks-DataCleaning)

### ISSUE THREAD

**Issue by JesusGuardiaRamirez** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#22]
https://github.com/JesusGuardiaRamirez/Sharks-DataCleaning

**Comment by OrianAmpuero** [comment]
Muy bien Jesus!! El código bien comentado pero cuidado con las decisiones que se toman ya que 'Name' por ejemplo sería mejor poner una string como 'unknown' que 0 que sería int . A pesar de que falta trabajo de limpieza , queda mejor exportar y guardar el csv como al final del notebook y en cuanto a los gráficos bien hecho para ver mejor que hay en los datos y tener mejor conocimiento. El readme bien, trata de adaptarlo más a ti, por ejemplo, cambiar la foto o algunos detalles y cuidado porque la estructura en el readme que esta no es la que tienes tú; guarda los archivos en carpetas.
