### ISSUE TITLE
[LORENZO IMIZCOZ](SharkAttack)

### ISSUE THREAD

**Issue by Lorensou** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#23]
https://github.com/Lorensou/SharkAttacks.git

**Comment by OrianAmpuero** [comment]
Bien Lorenzo! Hay que seguir trabajando para aplicar distintos métodos y funciones para limpiar con mayor detalle, te animo a seguir a tope. Te falta redactar readme y añadir carpetas para organizar los archivos.
