### ISSUE TITLE
[Guillermo Lozano Juanco](Proyecto_Pandas)

### ISSUE THREAD

**Issue by GuilleJuanco** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#24]
https://github.com/GuilleJuanco/Proyecto_Pandas

**Comment by OrianAmpuero** [comment]
Buen trabajo Guillermo! En cuanto a la limpieza esta trabajada y comentada, siempre se puede ir mejorando pero en principio vas bien. El readme trata de tenerlo mejor presentado visualmente, puedes ver guías de otros repos para ver ideas; así como los archivos separarlos en carpetas dependiendo de lo que sea y probar el gitignore para no subir el csv sucio
