### ISSUE TITLE
[Nerea Riveiro](w2-project_pandas)

### ISSUE THREAD

**Issue by NereaRiveiro** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#3]
https://github.com/NereaRiveiro/Proyecto-1_Sharkniceria.git

**Comment by OrianAmpuero** [comment]
Buen trabajo Nerea! Todo organizado y explicado en el readme, hay que seguir puliendo detalles de limpieza pero bien usado el importe de funciones.
