### ISSUE TITLE
[Anton Utray][w2-project_pandas]

### ISSUE THREAD

**Issue by Anton-Utray** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#4]
https://github.com/Anton-Utray/Sharknado.git

**Comment by CharlyKill7** [comment]
Muy buen proyecto, Anton! En general, has hecho un gran trabajo. Permíteme hacerte algunos comentarios:

-Buen repo en general, pero no deberías incluir los .csv. Asegúrate de incluirlos en el .gitignore. El readme está correcto, quizá algo escueto (es el mismo feedback de readme que me dieron a mí, por eso te lo digo, pero yo hice como tú y me parece suficiente).
-Me gusta mucho el orden de pensamiento que sigues, primero la exploración inicial, luego el manejo de nulos, después duplicados, etc. Intenta hacerlo parte de tu metodología. En ese sentido, muy bien el archivo de funciones.
-Usas str.capitalize().str.title(), y no estoy seguro de si entiendes bien esos dos métodos. Capitalize convierte la primera letra de la string en mayúscula y Title hace lo mismo con todas las palabras, y además asegura que el resto de la palabra sea minúscula. Es decir, no es necesario usar las dos, y parece mejor usar title que capitalize para tu propósito.
-También aplicas lstrip y rstrip a la misma columna en dos líneas, pero probablemente puedas usar strip y que te haga en un solo paso lo mismo que las otras dos. 
-Me gusta cómo atacas cada caso aunque tengas que hacerlo uno a uno. No es lo más eficiente, pero demuestra voluntad por dejar el DF justo como lo quieres. Hay quien después de hacer cambios generales no ha ido a por el caso particular, y tú sí y te felicito por ello. 
-Te sugiero que una vez has terminado la limpieza, antes de pasarlo a csv intentes convertir el tipo de dato que lo permita a category, y los int o float intenta ‘downcastearlos’ para que el DF quede optimizado y ocupe menos espacio en memoria.
-Al final, cuando conviertes tu DF en un nuevo csv limpio, acuérdate de usar el parámetro index=False para que no guarde el índice en el csv porque, si vuelves a cargar el limpio, verás que se ha generado una columna Unnamed 0 con el índice.

Como te he dicho, muy buen trabajo. Sigue en esta línea que vas de lujo!
