### ISSUE TITLE
[Carolina Rivera](w2-project_pandas)

### ISSUE THREAD

**Issue by carolinariveraa** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#5]

**Comment by carolinariveraa** [comment]
https://github.com/carolinariveraa/-CarolinaRivera-Sharks-

**Comment by CharlyKill7** [comment]
Gran proyecto, Carolina. Se nota que no sólo entiendes bien la parte de código, también se ve una mente bien amueblada. Algunos comentarios:

-	Muy bien el repo, está muy bien organizado. Tal vez el Readme sea un poco largo y haya demasiada explicación para lo que debería ser una sinopsis, pero yo después de varios proyectos sigo sin pillarle la medida. Eso sí, muy bien el ir commiteando el proyecto regularmente. Es una muy buena práctica.
-	Buen planteamiento mental, lo que se traduce en una buena organización. Se nota que tienes una estructura del proceso a seguir y eso viene genial.
-	Muy bien comentado el notebook, queda claro lo que intentas hacer en todo momento.
-	Te felicito por no quedarte en la superficie de muchas columnas y tirar de diccionarios trabajosos (también por la propia investigación) para rellenar columnas que no te sirven con datos que pueden servir para filtrar, por ejemplo, por estaciones.
-	El único “pero” te lo pongo al final. Si tiras un .info() verás varias cosas, como que se te pasó un nulo en ‘Case Number’ o que todas tus columnas son de tipo object. En los casos en los que sea posible estaría bien intentar convertir el tipo de dato a category (principalmente en strings), y hacer el “downcast” de los int y float que pudieras tener para optimizar el DF y reducir el espacio que ocupa en memoria. Por todo ello, intenta acabar como empezaste, explorando el DF final. 
-	En cuanto al notebook de visualización, no puedo más que felicitarte. Que ya estés explorando gráficos denota curiosidad y ganas de aprender, además de voluntad por no quedarte en la superficie y, ya que limpias, haces un pequeño análisis.

En general, un proyecto muy pulcro y completo. Enhorabuena y sigue así!
