### ISSUE TITLE
[Juan Nuñez](w2_projecto_pandas)

### ISSUE THREAD

**Issue by pizornpy** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#6]
https://github.com/pizornpy/Proyecto_Pandas_Tiburones.git

**Comment by OrianAmpuero** [comment]
Bien Juan!! Se podría trabajar más pero vas bien, te animo a seguir practicando los distintos métodos. El readme correcto aunque falta organizar algunos archivos en su carpeta
