### ISSUE TITLE
[Javier R.](w2-project_pandas)

### ISSUE THREAD

**Issue by jrodrisanz** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#7]
https://github.com/jrodrisanz/Proyecto_Sharks

**Comment by OrianAmpuero** [comment]
Buen trabajo Javier, bien comentado el código y a pesar de que aún se puede trabajar más, esta bien. En cuanto al repo todo correcto, el readme bien explicado. Pendiente de ese .gitignore (la extensión debería ser esa y no .txt)
