### ISSUE TITLE
[Juan Gouveia](w2-project_pandas)

### ISSUE THREAD

**Issue by JuanGouveia** [Ironhack-Data-Madrid-Abril-2023/w2-project_pandas#8]
https://github.com/JuanGouveia/Shark-Attacks-Project.git

**Comment by OrianAmpuero** [comment]
Muy buen trabajo juan! En cuanto al repo tiene readme y organización, esta muy bien. El código comentado y desarrollado pero hubiese sido mejor importar las funciones de tu archivo .py y solo llamarlo. Sigue así!!
